import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Archive, ArrowRight, Boxes, ChevronDown, CircleDollarSign, ClipboardList, LayoutDashboard, LogOut, Menu, Package, Pencil, Plus, Search, ShoppingBag, Users, X } from 'lucide-react';
import { api, ApiError, Contact, Product, StockRow, User } from './api';
import './styles.css';

type Page = 'login' | 'dashboard' | 'contacts' | 'products';
type Modal = { kind: 'contact'; item?: Contact } | { kind: 'product'; item?: Product };
const rupees = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value);

function App() {
  const [page, setPage] = useState<Page>('login'); const [user, setUser] = useState<User | null>(null);
  const [contacts, setContacts] = useState<Contact[]>([]); const [products, setProducts] = useState<Product[]>([]); const [stock, setStock] = useState<StockRow[]>([]);
  const [query, setQuery] = useState(''); const [modal, setModal] = useState<Modal | null>(null); const [toast, setToast] = useState(''); const [loading, setLoading] = useState(false);
  const flash = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3000); };
  const loadData = async () => { setLoading(true); try { const [me, loadedContacts, loadedProducts, loadedStock] = await Promise.all([api.currentUser(), api.contacts(), api.products(), api.stock()]); setUser(me); setContacts(loadedContacts); setProducts(loadedProducts); setStock(loadedStock); setPage('dashboard'); } catch (error) { api.logout(); setUser(null); setPage('login'); throw error; } finally { setLoading(false); } };
  useEffect(() => { void loadData().catch(() => undefined); }, []);
  const signIn = async (email: string, password: string) => { await api.login(email, password); await loadData(); flash('Signed in successfully'); };
  const logout = () => { api.logout(); setUser(null); setPage('login'); setContacts([]); setProducts([]); };
  const save = async (pending: Modal, values: Omit<Contact, 'id'> | Omit<Product, 'id'>) => { if (pending.kind === 'contact') { const record = pending.item ? await api.updateContact(pending.item.id, values as Omit<Contact, 'id'>) : await api.createContact(values as Omit<Contact, 'id'>); setContacts(items => pending.item ? items.map(item => item.id === record.id ? record : item) : [...items, record]); } else { const record = pending.item ? await api.updateProduct(pending.item.id, values as Omit<Product, 'id'>) : await api.createProduct(values as Omit<Product, 'id'>); setProducts(items => pending.item ? items.map(item => item.id === record.id ? record : item) : [...items, record]); setStock(await api.stock()); } setModal(null); flash('Saved successfully'); };
  const remove = async (kind: Modal['kind'], id: number) => { if (!window.confirm('Delete this record? This cannot be undone.')) return; if (kind === 'contact') { await api.deleteContact(id); setContacts(items => items.filter(item => item.id !== id)); } else { await api.deleteProduct(id); setProducts(items => items.filter(item => item.id !== id)); } flash('Record deleted'); };
  if (page === 'login') return <Login onLogin={signIn} loading={loading} />;
  return <div className="app-shell"><Sidebar page={page} user={user} onPage={setPage} onLogout={logout} /><main><header className="topbar"><button className="mobile-menu"><Menu size={20} /></button><div className="global-search"><Search size={18} /><input placeholder="Search current page..." value={query} onChange={event => setQuery(event.target.value)} /></div><div className="top-actions"><div className="avatar">{user?.name.slice(0, 2).toUpperCase()}</div></div></header>{page === 'dashboard' && <Dashboard contacts={contacts} products={products} stock={stock} onContacts={() => setPage('contacts')} onProducts={() => setPage('products')} />}{(page === 'contacts' || page === 'products') && <ListPage kind={page === 'contacts' ? 'contact' : 'product'} contacts={contacts} products={products} stock={stock} query={query} onAdd={() => setModal({ kind: page === 'contacts' ? 'contact' : 'product' })} onEdit={item => setModal({ kind: page === 'contacts' ? 'contact' : 'product', item } as Modal)} onDelete={id => void remove(page === 'contacts' ? 'contact' : 'product', id)} />}</main>{modal && <RecordModal modal={modal} onClose={() => setModal(null)} onSave={save} />} {toast && <div className="toast">{toast}</div>}</div>;
}

function Login({ onLogin, loading }: { onLogin: (email: string, password: string) => Promise<void>; loading: boolean }) { const [email, setEmail] = useState('admin@urbanfurniture.com'); const [password, setPassword] = useState('admin123'); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await onLogin(email, password); } catch (err) { setError(err instanceof ApiError ? err.message : 'Could not connect to the API'); } }; return <div className="register-page"><div className="register-art"><div className="brand"><div className="brand-mark">L</div>Pebble</div><div><p className="eyebrow">SMARTER ACCOUNTING, MADE SIMPLE</p><h1>Every number.<br /><em>One clear view.</em></h1><p>Run your finances, sales and operations from one workspace.</p></div></div><form className="register-card" onSubmit={submit}><div className="form-head"><span className="eyebrow">WELCOME TO PEBBLE</span><h2>Sign in</h2><p>Use the seeded administrator account to access the dashboard.</p></div><label>Work email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input required type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Connecting…' : <>Sign in <ArrowRight size={18} /></>}</button></form></div>; }

function Sidebar({ page, user, onPage, onLogout }: { page: Page; user: User | null; onPage: (page: Page) => void; onLogout: () => void }) { return <aside className="sidebar"><div className="brand"><div className="brand-mark">L</div><span>pebble</span></div><div className="workspace"><span className="dot" />Urban Furniture <ChevronDown size={15} /></div><nav><button className={page === 'dashboard' ? 'nav-item active' : 'nav-item'} onClick={() => onPage('dashboard')}><LayoutDashboard size={18} />Dashboard</button><button className={page === 'contacts' ? 'nav-item active' : 'nav-item'} onClick={() => onPage('contacts')}><Users size={18} />Contacts</button><button className={page === 'products' ? 'nav-item active' : 'nav-item'} onClick={() => onPage('products')}><Package size={18} />Products</button><button className="nav-item"><CircleDollarSign size={18} />Sales</button><button className="nav-item"><ShoppingBag size={18} />Purchase</button></nav><div className="sidebar-bottom"><button className="nav-item" onClick={onLogout}><LogOut size={18} />Sign out</button><div className="profile"><div className="avatar">{user?.name.slice(0, 2).toUpperCase()}</div><div><b>{user?.name}</b><small>{user?.role}</small></div></div></div></aside>; }

function Dashboard({ contacts, products, stock, onContacts, onProducts }: { contacts: Contact[]; products: Product[]; stock: StockRow[]; onContacts: () => void; onProducts: () => void }) { const units = stock.reduce((total, item) => total + item.current_stock, 0); return <div className="page dashboard"><div className="page-heading"><div><span className="eyebrow">OVERVIEW</span><h1>Urban Furniture</h1><p>Live data from your FastAPI backend.</p></div></div><div className="stat-grid"><Stat label="Contacts" value={String(contacts.length)} change="Customers & vendors" /><Stat label="Products" value={String(products.length)} change="Catalog items" /><Stat label="Stock on hand" value={`${units} units`} change="Purchase in − sale out" /><Stat label="API status" value="Connected" change="FastAPI on port 8000" /></div><section><div className="section-title"><div><h2>Accounts</h2><p>Manage records stored in the backend database.</p></div></div><div className="module-grid"><button className="module-card" onClick={onContacts}><div className="module-icon blue"><ClipboardList size={22} /></div><div><h3>Contacts</h3><p>Customers and vendors</p></div><ArrowRight size={18} /></button><button className="module-card" onClick={onProducts}><div className="module-icon orange"><Boxes size={22} /></div><div><h3>Products</h3><p>Prices and stock</p></div><ArrowRight size={18} /></button></div></section></div>; }
function Stat({ label, value, change }: { label: string; value: string; change: string }) { return <article className="stat"><span>{label}</span><strong>{value}</strong><small>{change}</small></article>; }

function ListPage({ kind, contacts, products, stock, query, onAdd, onEdit, onDelete }: { kind: 'contact' | 'product'; contacts: Contact[]; products: Product[]; stock: StockRow[]; query: string; onAdd: () => void; onEdit: (item: Contact | Product) => void; onDelete: (id: number) => void }) { const stockFor = (id: number) => stock.find(item => item.product_id === id)?.current_stock ?? 0; if (kind === 'product') { const filtered = products.filter(item => item.name.toLowerCase().includes(query.toLowerCase())); return <ListShell title="Products" count={filtered.length} onAdd={onAdd}>{filtered.map(item => <div className="table-row" key={item.id}><span className="name-cell"><div className="initial">{item.name.slice(0, 2).toUpperCase()}</div><b>{item.name}</b></span><span>{item.type}</span><span>{rupees(item.sales_price)}</span><span>{stockFor(item.id)} units</span><span /><span /><Actions onEdit={() => onEdit(item)} onDelete={() => onDelete(item.id)} /></div>)}</ListShell>; } const filtered = contacts.filter(item => item.name.toLowerCase().includes(query.toLowerCase())); return <ListShell title="Contacts" count={filtered.length} onAdd={onAdd}>{filtered.map(item => <div className="table-row" key={item.id}><span className="name-cell"><div className="initial">{item.name.slice(0, 2).toUpperCase()}</div><b>{item.name}</b></span><span>{item.type}</span><span>{item.email ?? '—'}</span><span>{item.mobile ?? '—'}</span><span /><span /><Actions onEdit={() => onEdit(item)} onDelete={() => onDelete(item.id)} /></div>)}</ListShell>; }
function ListShell({ title, count, onAdd, children }: { title: string; count: number; onAdd: () => void; children: React.ReactNode }) { return <div className="page list-page"><div className="breadcrumb">Account <span>/</span> {title}</div><div className="list-heading"><div><h1>{title}</h1><p>Manage {title.toLowerCase()} stored in the backend.</p></div><button className="primary compact" onClick={onAdd}><Plus size={17} />Add {title === 'Products' ? 'product' : 'contact'}</button></div><div className="table-panel"><div className="count">{count} {title.toLowerCase()}</div><div className="data-table"><div className="table-row table-head"><span>{title === 'Products' ? 'PRODUCT' : 'CONTACT'}</span><span>TYPE</span><span>{title === 'Products' ? 'SALE PRICE' : 'EMAIL'}</span><span>{title === 'Products' ? 'IN STOCK' : 'MOBILE'}</span><span /><span /><span /></div>{children}</div></div></div>; }
function Actions({ onEdit, onDelete }: { onEdit: () => void; onDelete: () => void }) { return <span className="row-actions"><button title="Edit" onClick={onEdit}><Pencil size={16} /></button><button title="Delete" onClick={onDelete}><Archive size={16} /></button></span>; }

function RecordModal({ modal, onClose, onSave }: { modal: Modal; onClose: () => void; onSave: (modal: Modal, values: Omit<Contact, 'id'> | Omit<Product, 'id'>) => Promise<void> }) { const isProduct = modal.kind === 'product'; const item = modal.item; const contact = isProduct ? undefined : item as Contact | undefined; const product = isProduct ? item as Product | undefined : undefined; const [name, setName] = useState(item?.name ?? ''); const [email, setEmail] = useState(contact?.email ?? ''); const [mobile, setMobile] = useState(contact?.mobile ?? ''); const [type, setType] = useState<string>(item?.type ?? (isProduct ? 'GOODS' : 'CUSTOMER')); const [salesPrice, setSalesPrice] = useState(product ? String(product.sales_price) : ''); const [purchasePrice, setPurchasePrice] = useState(product ? String(product.purchase_price) : ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await onSave(modal, isProduct ? { name, type: type as Product['type'], sales_price: Number(salesPrice), purchase_price: Number(purchasePrice), category_id: null } : { name, type: type as Contact['type'], email: email || null, mobile: mobile || null }); } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to save record'); setSaving(false); } }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={onClose}><X /></button><span className="eyebrow">ACCOUNT / {isProduct ? 'PRODUCTS' : 'CONTACTS'}</span><h2>{item ? 'Edit' : 'Create'} {modal.kind}</h2><label>Name<input autoFocus required value={name} onChange={event => setName(event.target.value)} /></label><label>Type<select value={type} onChange={event => setType(event.target.value)}>{(isProduct ? ['GOODS', 'SERVICE', 'COMBO'] : ['CUSTOMER', 'VENDOR', 'BOTH']).map(value => <option key={value}>{value}</option>)}</select></label>{isProduct ? <><label>Sales price<input required min="0" step="0.01" type="number" value={salesPrice} onChange={event => setSalesPrice(event.target.value)} /></label><label>Purchase price<input required min="0" step="0.01" type="number" value={purchasePrice} onChange={event => setPurchasePrice(event.target.value)} /></label></> : <><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label>Mobile<input value={mobile} onChange={event => setMobile(event.target.value)} /></label></>}{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button></div></form></div>; }
createRoot(document.getElementById('root')!).render(<App />);
