from datetime import date as date_cls
from typing import Optional, List
from pydantic import BaseModel, EmailStr, ConfigDict

from Backend.models import (
    UserRole, ContactType, ProductType, AccountType, TxnStatus,
    PaymentType, PaymentMethod, AnalyticType, StockMovementType
)


# ---------- Auth ----------

class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class UserOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    name: str
    email: str
    role: UserRole


class UserCreate(BaseModel):
    name: str
    email: EmailStr
    password: str
    role: UserRole


# ---------- Contact ----------

class ContactBase(BaseModel):
    name: str
    type: ContactType
    email: Optional[str] = None
    mobile: Optional[str] = None
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    pincode: Optional[str] = None


class ContactCreate(ContactBase):
    pass


class ContactUpdate(ContactBase):
    pass


class ContactOut(ContactBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Category ----------

class CategoryBase(BaseModel):
    name: str


class CategoryCreate(CategoryBase):
    pass


class CategoryOut(CategoryBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Product ----------

class ProductBase(BaseModel):
    name: str
    type: ProductType
    sales_price: float
    purchase_price: float
    category_id: Optional[int] = None


class ProductCreate(ProductBase):
    pass


class ProductUpdate(ProductBase):
    pass


class ProductOut(ProductBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Account ----------

class AccountBase(BaseModel):
    code: str
    name: str
    type: AccountType


class AccountCreate(AccountBase):
    pass


class AccountUpdate(AccountBase):
    pass


class AccountOut(AccountBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Journal ----------

class JournalBase(BaseModel):
    name: str
    type: str
    default_debit_account_id: Optional[int] = None
    default_credit_account_id: Optional[int] = None


class JournalCreate(JournalBase):
    pass


class JournalUpdate(JournalBase):
    pass


class JournalOut(JournalBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Sale ----------

class SaleCreate(BaseModel):
    customer_id: int
    product_id: int
    quantity: float
    unit_price: Optional[float] = None  # if omitted, backend uses product.sales_price
    tax_percent: Optional[float] = 0.0  # e.g. 18 for 18%
    date: Optional[date_cls] = None


class SaleOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    customer_id: int
    product_id: int
    quantity: float
    unit_price: float
    tax: float
    total: float
    date: date_cls
    status: TxnStatus


# ---------- Purchase ----------

class PurchaseCreate(BaseModel):
    vendor_id: int
    product_id: int
    quantity: float
    unit_price: Optional[float] = None  # if omitted, backend uses product.purchase_price
    tax_percent: Optional[float] = 0.0
    date: Optional[date_cls] = None


class PurchaseOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    vendor_id: int
    product_id: int
    quantity: float
    unit_price: float
    tax: float
    total: float
    date: date_cls
    status: TxnStatus


# ---------- Payment ----------

class PaymentCreate(BaseModel):
    contact_id: int
    reference_id: Optional[int] = None  # Sale id (if RECEIVE) or Purchase id (if PAY)
    type: PaymentType
    method: PaymentMethod
    amount: float
    date: Optional[date_cls] = None


class PaymentOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    contact_id: int
    reference_id: Optional[int]
    type: PaymentType
    method: PaymentMethod
    amount: float
    date: date_cls


# ---------- Journal Entry / Item (read-only, generated by system) ----------

class JournalItemOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    account_id: int
    debit: float
    credit: float


class JournalEntryOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    journal_id: int
    date: date_cls
    reference: Optional[str]
    description: Optional[str]
    items: List[JournalItemOut] = []


# ---------- Analytic Account ----------

class AnalyticAccountBase(BaseModel):
    name: str
    type: AnalyticType


class AnalyticAccountCreate(AnalyticAccountBase):
    pass


class AnalyticAccountOut(AnalyticAccountBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Budget ----------

class BudgetBase(BaseModel):
    name: str
    period_start: date_cls
    period_end: date_cls
    responsible_person: Optional[str] = None
    analytic_account_id: int
    planned_amount: float


class BudgetCreate(BudgetBase):
    pass


class BudgetUpdate(BudgetBase):
    pass


class BudgetOut(BudgetBase):
    model_config = ConfigDict(from_attributes=True)
    id: int


# ---------- Stock Movement ----------

class StockMovementOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    product_id: int
    type: StockMovementType
    quantity: float
    reference_id: Optional[int]
    date: date_cls


# ---------- AI ----------

class AnalyzeReportRequest(BaseModel):
    report_type: str
    data: dict


class AnalyzeReportResponse(BaseModel):
    report_type: str
    analysis: str
